name: firebase_admin_sdk_workspace
publish_to: none

environment:
  sdk: ^3.9.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  melos: ^8.0.0
  test: ^1.26.3

workspace:
  - packages/firebase_admin_sdk
  - packages/firebase_admin_sdk/example
  - packages/firebase_admin_sdk/example_server_app
  - packages/google_cloud_firestore

melos:
  scripts:
    docs:
      description: Generate documentation for all packages
      exec:
        command: $MELOS_ROOT_PATH/scripts/generate-docs.sh
        concurrency: 1
      select-package:
        - '*'
      packageFilters:
        flutter: false
        ignore:
          - "*example*"

  command:
    bootstrap:
      hooks:
        post: ./scripts/gen-version.sh
    version:
      hooks:
        post: ./scripts/gen-version.sh
