// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/// Compares the Pipeline requests this SDK sends with the ones the Node.js
/// SDK sends for the same Pipelines.
///
/// The expected requests in `test/fixtures/pipeline_golden/*.json` are
/// generated by the Node.js SDK (see `tool/pipeline_golden/README.md`), never
/// by this package. Every fixture id has a Dart case below that builds the
/// equivalent Pipeline; the request it sends must equal the fixture.
///
/// When this SDK deliberately sends something else, the id is listed in
/// [_knownDivergences]. Differences that look like bugs, still to be fixed,
/// are listed in [_pendingFixes]. Node APIs with no Dart equivalent are
/// listed in [_dartApiGaps]. All three lists are checked: an entry fails as
/// soon as it no longer describes reality.
library;

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:google_cloud_firestore/google_cloud_firestore.dart';
import 'package:google_cloud_firestore/src/firestore_http_client.dart';
import 'package:google_cloud_firestore_v1/firestore.dart' as firestore_v1;
import 'package:google_cloud_firestore_v1/testing.dart';
import 'package:mocktail/mocktail.dart';
import 'package:test/test.dart' hide greaterThan, lessThan;

const _projectId = 'test-project';
const _databaseId = '(default)';
const _fixtureDir = 'test/fixtures/pipeline_golden';

class _MockFirestoreHttpClient extends Mock implements FirestoreHttpClient {}

/// Where this SDK deliberately sends something other than the Node SDK.
///
/// [_Divergence.check] asserts the Dart request still has the intended shape.
final _knownDivergences = <String, _Divergence>{
  for (final name in [
    'equalAny',
    'notEqualAny',
    'arrayContainsAll',
    'arrayContainsAny',
  ])
    for (final variant in [
      'static-field-name-list-with-expression',
      'method-list-with-expression',
    ])
      'functions/$name/$variant': const _Divergence(
        'A search-space list holding expressions is sent as an array(...) '
        'function. Node sends a literal arrayValue holding a field '
        'reference, which the backend rejects ("Value type is not '
        'supported: FIELD_REFERENCE_VALUE").',
        _searchSpaceIsArrayFunction,
      ),
};

/// Differences from the Node SDK that are not intended, awaiting a fix.
///
/// Each entry must still differ from its fixture; remove it once fixed.
const _pendingFixes = <String, String>{
  // field() sends the path verbatim; Node formats it like FieldPath, quoting
  // segments that are not simple identifiers.
  'values/field/special-characters':
      "field('first-name') sends `first-name` unquoted; Node sends "
      '"`first-name`".',
  'values/field/space':
      "field('last name') sends `last name` unquoted; Node sends "
      '"`last name`".',
  'values/field/non-ascii':
      "field('naïve') sends `naïve` unquoted; Node sends \"`naïve`\".",
  'stages/select/special-characters':
      'select() leaves special-character field paths unquoted; Node quotes '
      'them, and keys a PipelineField by its quoted path ("`last name`").',
  // Ordering helpers.
  // Query to Pipeline conversion.
  'queries/where/not-equal':
      "createFrom(query) leaves '!=' fields out of the implicit sort; "
      'Node sorts by them before __name__ (isInequalityFilter omits '
      'notEqual).',
  'queries/where/not-equal-null':
      "createFrom(query) leaves '!= null' fields out of the implicit sort; "
      'Node sorts by them before __name__.',
  'queries/where/not-in':
      "createFrom(query) leaves 'not-in' fields out of the implicit sort; "
      'Node sorts by them before __name__ (isInequalityFilter omits notIn).',
  'queries/vector/distance-result-field':
      'createFrom(vectorQuery) sends a distance_field option; Node drops '
      'distanceResultField. Dart keeps the query semantics: decide whether '
      'this should be a known divergence.',
  'queries/vector/distance-threshold':
      'createFrom(vectorQuery) sends a distance_threshold option; Node drops '
      'distanceThreshold and its find_nearest stage has no such option, so '
      'the backend name is unverified.',
  // Nested plain collections. Node turns a nested list or map into an
  // array(...) / map(...) function; Dart sends a nested literal.
  'functions/equalAny/static-field-name-list-nested':
      "A nested list in the search space (['Fantasy', ['Sci-Fi']]) is sent "
      'as a literal arrayValue; Node sends an array(...) function inside the '
      'literal arrayValue (the known-divergence family: prod likely rejects '
      "Node's form).",
  'functions/notEqualAny/static-field-name-list-nested':
      'As equalAny: nested literal arrayValue vs Node array(...) function.',
  'functions/arrayContainsAll/static-field-name-list-nested':
      'As equalAny: nested literal arrayValue vs Node array(...) function.',
  'functions/arrayContainsAny/static-field-name-list-nested':
      'As equalAny: nested literal arrayValue vs Node array(...) function.',
};

/// Node APIs this SDK has no way to express; there is no Dart case for them.
const _dartApiGaps = <String, String>{
  'sources/subcollection/as-array-expression':
      'No subcollection() source and no Pipeline.toArrayExpression().',
  'stages/define/plain': 'No Pipeline.define (let) stage.',
  'stages/delete/plain': 'No Pipeline.delete stage.',
  'stages/update/plain': 'No Pipeline.update stage.',
  'stages/to-scalar-expression/plain': 'No Pipeline.toScalarExpression().',
  'values/field/field-path-object': 'field() takes a String, not a FieldPath.',
  'functions/add/method-variadic':
      'PipelineExpression.add takes a single operand.',
  'functions/multiply/method-variadic':
      'PipelineExpression.multiply takes a single operand.',
  'functions/arraySlice/static-field-name-offset':
      'PipelineFunctions.arraySlice requires a length; only the '
      'PipelineExpression.arraySlice method makes it optional.',
};

void main() {
  final fixtures = _loadFixtures();
  final registry = _Registry();
  _registerCases(registry);

  group('Node golden corpus', () {
    test('every fixture has a Dart case or a documented API gap', () {
      final missing = [
        for (final id in fixtures.keys)
          if (!registry.cases.containsKey(id) && !_dartApiGaps.containsKey(id))
            id,
      ];
      expect(
        missing,
        isEmpty,
        reason:
            'Add a Dart case to _registerCases for each of these fixture '
            'ids, or list it in _dartApiGaps.',
      );
    });

    test('every Dart case has a fixture', () {
      final orphans = [
        for (final id in registry.cases.keys)
          if (!fixtures.containsKey(id)) id,
      ];
      expect(
        orphans,
        isEmpty,
        reason:
            'Add these cases to tool/pipeline_golden/cases.js and regenerate '
            'the fixtures (see tool/pipeline_golden/README.md).',
      );
    });

    test('documented API gaps have a fixture and no Dart case', () {
      for (final id in _dartApiGaps.keys) {
        expect(fixtures, contains(id), reason: '_dartApiGaps lists $id');
        expect(
          registry.cases,
          isNot(contains(id)),
          reason: '$id has a Dart case: remove it from _dartApiGaps.',
        );
      }
    });

    test('divergences and pending fixes have a fixture and a Dart case', () {
      for (final id in [..._knownDivergences.keys, ..._pendingFixes.keys]) {
        expect(fixtures, contains(id));
        expect(registry.cases, contains(id));
      }
      expect(
        _knownDivergences.keys.toSet().intersection(_pendingFixes.keys.toSet()),
        isEmpty,
      );
    });
  });

  group('matches the Node SDK request', () {
    late _MockFirestoreHttpClient client;
    late Firestore db;
    firestore_v1.ExecutePipelineRequest? captured;

    setUp(() {
      client = _MockFirestoreHttpClient();
      when(() => client.cachedProjectId).thenReturn(_projectId);
      when(
        () => client.v1<Stream<firestore_v1.ExecutePipelineResponse>>(any()),
      ).thenAnswer((invocation) async {
        final callback =
            invocation.positionalArguments.single
                as Future<Stream<firestore_v1.ExecutePipelineResponse>>
                Function(firestore_v1.Firestore api, String projectId);
        final api = FakeFirestore(
          executePipeline: (request) {
            captured = request;
            return const Stream<firestore_v1.ExecutePipelineResponse>.empty();
          },
        );
        return callback(api, _projectId);
      });
      db = Firestore.internal(
        settings: const Settings(
          projectId: _projectId,
          databaseId: _databaseId,
        ),
        client: client,
      );
    });

    Future<Object?> capture(_Run run) async {
      captured = null;
      await run(db);
      final request = captured;
      if (request == null) fail('The case sent no request.');
      return _canonicalize(jsonDecode(jsonEncode(request.toJson())));
    }

    for (final id in fixtures.keys.toList()..sort()) {
      final runs = registry.cases[id];
      if (runs == null) continue;
      final expected = fixtures[id];

      test(id, () async {
        for (final (index, run) in runs.indexed) {
          final actual = await capture(run);
          final form = runs.length == 1 ? '' : ' (Dart form #${index + 1})';
          final differences = <String>[];
          _diff(expected, actual, r'$', differences);

          final divergence = _knownDivergences[id];
          final pending = _pendingFixes[id];
          if (divergence != null) {
            expect(
              differences,
              isNotEmpty,
              reason:
                  '$id$form now matches Node: remove it from '
                  '_knownDivergences.',
            );
            expect(
              divergence.check(actual),
              isTrue,
              reason:
                  '$id$form no longer has the intended shape: '
                  '${divergence.reason}\n'
                  'Dart sent:\n${_pretty(actual)}',
            );
          } else if (pending != null) {
            expect(
              differences,
              isNotEmpty,
              reason:
                  '$id$form now matches Node: remove it from '
                  '_pendingFixes.',
            );
          } else if (differences.isNotEmpty) {
            fail(
              '$id$form differs from the Node SDK request:\n'
              '  ${differences.join('\n  ')}\n\n'
              'Dart sent:\n${_pretty(actual)}\n\n'
              'Node sent:\n${_pretty(expected)}',
            );
          }
        }
      });
    }
  });
}

// -----------------------------------------------------------------------------
// Fixtures and comparison
// -----------------------------------------------------------------------------

/// Loads every case of every fixture file, keyed by id.
Map<String, Object?> _loadFixtures() {
  final files =
      Directory(_fixtureDir)
          .listSync()
          .whereType<File>()
          .where((file) => file.path.endsWith('.json'))
          .toList()
        ..sort((a, b) => a.path.compareTo(b.path));
  if (files.isEmpty) {
    throw StateError('No fixtures in $_fixtureDir; run from the package root.');
  }

  final result = <String, Object?>{};
  for (final file in files) {
    final json = jsonDecode(file.readAsStringSync()) as Map<String, Object?>;
    final cases = json['cases']! as Map<String, Object?>;
    for (final MapEntry(:key, :value) in cases.entries) {
      if (result.containsKey(key)) {
        throw StateError('Duplicate fixture id $key in ${file.path}.');
      }
      result[key] = _canonicalize(value);
    }
  }
  return result;
}

/// Repeated and map fields that proto3 JSON omits when empty.
///
/// The same normalization `tool/pipeline_golden/generate.js` applies.
const _omitWhenEmpty = {'args', 'options', 'fields', 'values'};

/// Sorts keys (`name` first, as in the fixtures) and drops [_omitWhenEmpty]
/// fields that are empty.
Object? _canonicalize(Object? value) {
  return switch (value) {
    List() => [for (final item in value) _canonicalize(item)],
    Map() => {
      for (final key in value.keys.cast<String>().toList()..sort(_compareKeys))
        if (_canonicalize(value[key]) case final child
            when !(_omitWhenEmpty.contains(key) && _isEmpty(child)))
          key: child,
    },
    _ => value,
  };
}

int _compareKeys(String a, String b) {
  if (a == b) return 0;
  if (a == 'name') return -1;
  if (b == 'name') return 1;
  return a.compareTo(b);
}

bool _isEmpty(Object? value) {
  return switch (value) {
    List() => value.isEmpty,
    Map() => value.isEmpty,
    _ => false,
  };
}

/// Lists the paths at which [expected] and [actual] differ.
///
/// Numbers compare by value, so `1` and `1.0` (a `doubleValue` encoded by
/// JavaScript and by Dart) are equal.
void _diff(Object? expected, Object? actual, String path, List<String> out) {
  if (expected is Map && actual is Map) {
    for (final key in {...expected.keys, ...actual.keys}) {
      final child = '$path.$key';
      if (!expected.containsKey(key)) {
        out.add('$child: missing in Node, Dart has ${_short(actual[key])}');
      } else if (!actual.containsKey(key)) {
        out.add('$child: Node has ${_short(expected[key])}, missing in Dart');
      } else {
        _diff(expected[key], actual[key], child, out);
      }
    }
  } else if (expected is List && actual is List) {
    if (expected.length != actual.length) {
      out.add(
        '$path: Node has ${expected.length} items, Dart has '
        '${actual.length}: Node ${_short(expected)}, Dart ${_short(actual)}',
      );
      return;
    }
    for (var i = 0; i < expected.length; i++) {
      _diff(expected[i], actual[i], '$path[$i]', out);
    }
  } else if (expected != actual) {
    out.add('$path: Node ${_short(expected)}, Dart ${_short(actual)}');
  }
}

String _short(Object? value) {
  final json = jsonEncode(value);
  return json.length <= 200 ? json : '${json.substring(0, 200)}...';
}

String _pretty(Object? value) =>
    const JsonEncoder.withIndent('  ').convert(value);

/// A deliberate difference from the Node SDK.
final class _Divergence {
  const _Divergence(this.reason, this.check);

  /// Why this SDK sends something else.
  final String reason;

  /// Whether the canonical Dart request has the intended shape.
  final bool Function(Object? request) check;
}

/// Whether the `where` stage's function receives its search space as an
/// `array(...)` function.
bool _searchSpaceIsArrayFunction(Object? request) {
  final stages = _path(request, ['structuredPipeline', 'pipeline', 'stages']);
  if (stages is! List || stages.length != 2) return false;
  final searchSpace = _path(stages[1], ['args', 0, 'functionValue', 'args', 1]);
  return _path(searchSpace, ['functionValue', 'name']) == 'array';
}

Object? _path(Object? value, List<Object> path) {
  var current = value;
  for (final segment in path) {
    current = switch ((current, segment)) {
      (final Map<Object?, Object?> map, final String key) => map[key],
      (final List<Object?> list, final int index) when index < list.length =>
        list[index],
      _ => null,
    };
  }
  return current;
}

// -----------------------------------------------------------------------------
// Case registry
// -----------------------------------------------------------------------------

/// Executes a Pipeline against [db]; the request it sends is captured.
typedef _Run = Future<Object?> Function(Firestore db);

typedef _Build = Pipeline Function(Firestore db);
typedef _Expr = PipelineExpression Function();
typedef _DbExpr = PipelineExpression Function(Firestore db);
typedef _Static1 = PipelineExpression Function(Object? target);
typedef _Method0 = PipelineExpression Function(PipelineExpression target);
typedef _Static2 = PipelineExpression Function(Object? target, Object? operand);
typedef _Method1 =
    PipelineExpression Function(PipelineExpression target, Object? operand);

/// The Dart cases, keyed by fixture id.
///
/// A case may have several Dart forms (for example a top-level helper and
/// the matching [PipelineFunctions] member); each one must match.
final class _Registry {
  final cases = <String, List<_Run>>{};

  void run(String id, List<_Run> runs) {
    if (cases.containsKey(id)) throw StateError('Duplicate case id $id.');
    cases[id] = runs;
  }

  /// A Pipeline executed without options.
  void pipeline(
    String id,
    _Build build, [
    List<_Build> alternatives = const [],
  ]) {
    run(id, [
      for (final b in [build, ...alternatives]) (db) => b(db).execute(),
    ]);
  }

  /// A function wrapped as in `cases.js`: boolean expressions in `where`,
  /// everything else in `select(<expr>.as('result'))`.
  void expr(String id, _Expr build, [List<_Expr> alternatives = const []]) {
    pipeline(id, (db) => _wrap(db, build()), [
      for (final b in alternatives) (db) => _wrap(db, b()),
    ]);
  }

  /// A function that needs the Firestore instance, such as for a reference.
  void dbExpr(String id, _DbExpr build) {
    pipeline(id, (db) => _wrap(db, build(db)));
  }

  /// An aggregate function, in `aggregate(<expr>.as('result'))`.
  void aggregate(
    String id,
    _Expr build, [
    List<_Expr> alternatives = const [],
  ]) {
    pipeline(id, (db) => _books(db).aggregate([build().as('result')]), [
      for (final b in alternatives)
        (db) => _books(db).aggregate([b().as('result')]),
    ]);
  }

  /// Mirrors `unary` in `cases.js`.
  void unary(
    String name,
    String target,
    _Static1 static,
    _Method0 method, {
    String area = 'functions',
  }) {
    final register = area == 'aggregates' ? aggregate : expr;
    register('$area/$name/static-field-name', () => static(target));
    register('$area/$name/static-expression', () => static(field(target)));
    register('$area/$name/method', () => method(field(target)));
  }

  /// Mirrors `binary` in `cases.js`.
  void binary(
    String name,
    String target,
    Object? literal,
    _Expr operand,
    _Static2 static,
    _Method1 method, {
    List<_Static2> staticAlternatives = const [],
    List<_Method1> methodAlternatives = const [],
  }) {
    final statics = [static, ...staticAlternatives];
    final methods = [method, ...methodAlternatives];
    void staticCase(
      String variant,
      Object? Function() target,
      Object? Function() op,
    ) {
      expr('functions/$name/static-$variant', () => static(target(), op()), [
        for (final s in statics.skip(1)) () => s(target(), op()),
      ]);
    }

    staticCase('field-name-literal', () => target, () => literal);
    staticCase('field-name-expression', () => target, operand);
    staticCase('expression-literal', () => field(target), () => literal);
    staticCase('expression-expression', () => field(target), operand);
    expr(
      'functions/$name/method-literal',
      () => method(field(target), literal),
      [for (final m in methods.skip(1)) () => m(field(target), literal)],
    );
    expr(
      'functions/$name/method-expression',
      () => method(field(target), operand()),
    );
  }
}

Pipeline _books(Firestore db) => db.pipeline().collection('books');

Pipeline _wrap(Firestore db, PipelineExpression expression) {
  return switch (expression) {
    PipelineBooleanExpression() => _books(db).where(expression),
    _ => _books(db).select([expression.as('result')]),
  };
}

// Fixed values, identical to the ones in `cases.js`.
final _timestamp = Timestamp(seconds: 1700000000, nanoseconds: 123456789);
final _date = DateTime.utc(2024, 1, 2, 3, 4, 5, 678);
final _geoPoint = GeoPoint(latitude: 37.7749, longitude: -122.4194);
final _bytes = Uint8List.fromList([1, 2, 3, 255]);
final _vector = FieldValue.vector([0.1, 0.2, 0.3]);
DocumentReference<DocumentData> _docRef(Firestore db) => db.doc('books/book1');

PipelineBooleanExpression _isFantasy() => field('genre').equal('Fantasy');
PipelineBooleanExpression _isGood() => field('rating').greaterThan(4);
PipelineBooleanExpression _isOld() => field('published').lessThan(1950);

void _registerCases(_Registry r) {
  _registerSources(r);
  _registerQueries(r);
  _registerStages(r);
  _registerOptions(r);
  _registerValues(r);
  _registerArithmetic(r);
  _registerComparisonAndLogic(r);
  _registerStrings(r);
  _registerArrays(r);
  _registerMaps(r);
  _registerTimestamps(r);
  _registerTypesVectorsAndReferences(r);
  _registerAggregates(r);
}

// -----------------------------------------------------------------------------
// Sources and queries
// -----------------------------------------------------------------------------

void _registerSources(_Registry r) {
  r.pipeline(
    'sources/collection/path',
    (db) => db.pipeline().collection('books'),
  );
  r.pipeline(
    'sources/collection/nested-path',
    (db) => db.pipeline().collection('authors/author1/books'),
  );
  r.pipeline(
    'sources/collection/reference',
    (db) => db.pipeline().collectionReference(db.collection('books')),
  );
  r.pipeline(
    'sources/collection-group/id',
    (db) => db.pipeline().collectionGroup('reviews'),
  );
  // Dart has no typed forceIndex (a pending fix in the API parity test), but
  // rawOptions sends the same option.
  r.pipeline(
    'sources/collection/force-index',
    (db) => db.pipeline().collection(
      'books',
      rawOptions: const {'force_index': 'my_index'},
    ),
  );
  r.pipeline(
    'sources/collection/raw-options',
    (db) => db.pipeline().collection(
      'books',
      rawOptions: const {'foo': 'bar', 'outer.inner': 1},
    ),
  );
  r.pipeline(
    'sources/collection/reference-raw-options',
    (db) => db.pipeline().collectionReference(
      db.collection('books'),
      rawOptions: const {'foo': 'bar'},
    ),
  );
  r.pipeline(
    'sources/collection-group/force-index',
    (db) => db.pipeline().collectionGroup(
      'reviews',
      rawOptions: const {'force_index': 'my_index'},
    ),
  );
  r.pipeline(
    'sources/collection-group/raw-options',
    (db) => db.pipeline().collectionGroup(
      'reviews',
      rawOptions: const {'foo': 'bar'},
    ),
  );
  r.pipeline('sources/database/plain', (db) => db.pipeline().database());
  r.pipeline(
    'sources/database/raw-options',
    (db) => db.pipeline().database(rawOptions: const {'foo': 'bar'}),
  );
  // Dart only takes references; Node turns its paths into references.
  r.pipeline(
    'sources/documents/paths',
    (db) =>
        db.pipeline().documents([db.doc('books/book1'), db.doc('books/book2')]),
  );
  r.pipeline(
    'sources/documents/references',
    (db) =>
        db.pipeline().documents([db.doc('books/book1'), db.doc('books/book2')]),
  );
  r.pipeline(
    'sources/documents/nested',
    (db) => db.pipeline().documents([db.doc('authors/author1/books/book1')]),
  );
  r.pipeline(
    'sources/documents/raw-options',
    (db) => db.pipeline().documents(
      [db.doc('books/book1')],
      rawOptions: const {'foo': 'bar'},
    ),
  );
}

void _registerQueries(_Registry r) {
  void query(String id, Object Function(Firestore db) build) {
    r.pipeline('queries/$id', (db) => db.pipeline().createFrom(build(db)));
  }

  CollectionReference<DocumentData> col(Firestore db) => db.collection('books');

  query('collection/plain', col);
  query(
    'collection/nested-path',
    (db) => db.collection('authors/author1/books'),
  );
  query('collection-group/plain', (db) => db.collectionGroup('reviews'));
  query(
    'collection-group/where',
    (db) => db
        .collectionGroup('reviews')
        .where('rating', WhereFilter.greaterThan, 3),
  );

  query(
    'where/less-than',
    (db) => col(db).where('rating', WhereFilter.lessThan, 4),
  );
  query(
    'where/less-than-or-equal',
    (db) => col(db).where('rating', WhereFilter.lessThanOrEqual, 4),
  );
  query(
    'where/equal',
    (db) => col(db).where('genre', WhereFilter.equal, 'Fantasy'),
  );
  query(
    'where/not-equal',
    (db) => col(db).where('genre', WhereFilter.notEqual, 'Fantasy'),
  );
  query(
    'where/greater-than-or-equal',
    (db) => col(db).where('rating', WhereFilter.greaterThanOrEqual, 4),
  );
  query(
    'where/greater-than',
    (db) => col(db).where('rating', WhereFilter.greaterThan, 4),
  );
  query(
    'where/array-contains',
    (db) => col(db).where('tags', WhereFilter.arrayContains, 'magic'),
  );
  query(
    'where/in',
    (db) => col(db).where('genre', WhereFilter.isIn, ['Fantasy', 'Sci-Fi']),
  );
  query(
    'where/not-in',
    (db) => col(db).where('genre', WhereFilter.notIn, ['Fantasy', 'Sci-Fi']),
  );
  query(
    'where/array-contains-any',
    (db) =>
        col(db).where('tags', WhereFilter.arrayContainsAny, ['magic', 'epic']),
  );
  query(
    'where/equal-null',
    (db) => col(db).where('genre', WhereFilter.equal, null),
  );
  query(
    'where/not-equal-null',
    (db) => col(db).where('genre', WhereFilter.notEqual, null),
  );
  query(
    'where/equal-nan',
    (db) => col(db).where('rating', WhereFilter.equal, double.nan),
  );
  query(
    'where/double',
    (db) => col(db).where('rating', WhereFilter.greaterThan, 4.5),
  );
  query(
    'where/timestamp',
    (db) => col(db).where('published', WhereFilter.lessThan, _timestamp),
  );
  query(
    'where/nested-field',
    (db) => col(db).where('metadata.lang', WhereFilter.equal, 'en'),
  );
  query(
    'where/special-characters',
    (db) => col(db).where('first-name', WhereFilter.equal, 'Ada'),
  );
  query(
    'where/document-id',
    // Node also accepts the bare ID 'book1'; Dart's Query.where requires the
    // reference it resolves to.
    (db) => col(
      db,
    ).where(FieldPath.documentId, WhereFilter.equal, col(db).doc('book1')),
  );
  query(
    'where/multiple',
    (db) => col(db)
        .where('genre', WhereFilter.equal, 'Fantasy')
        .where('rating', WhereFilter.greaterThan, 4),
  );
  query(
    'where/composite-and',
    (db) => col(db).whereFilter(
      Filter.and([
        Filter.where('genre', WhereFilter.equal, 'Fantasy'),
        Filter.where('rating', WhereFilter.greaterThan, 4),
      ]),
    ),
  );
  query(
    'where/composite-or',
    (db) => col(db).whereFilter(
      Filter.or([
        Filter.where('genre', WhereFilter.equal, 'Fantasy'),
        Filter.where('rating', WhereFilter.greaterThan, 4),
      ]),
    ),
  );
  query(
    'where/composite-nested',
    (db) => col(db).whereFilter(
      Filter.or([
        Filter.and([
          Filter.where('genre', WhereFilter.equal, 'Fantasy'),
          Filter.where('rating', WhereFilter.greaterThan, 4),
        ]),
        Filter.where('published', WhereFilter.lessThan, 1950),
      ]),
    ),
  );

  query('order-by/ascending', (db) => col(db).orderBy('rating'));
  query(
    'order-by/descending',
    (db) => col(db).orderBy('rating', descending: true),
  );
  query(
    'order-by/multiple',
    (db) => col(db).orderBy('rating', descending: true).orderBy('title'),
  );
  query('order-by/document-id', (db) => col(db).orderBy(FieldPath.documentId));
  query('order-by/special-characters', (db) => col(db).orderBy('first-name'));
  query(
    'order-by/implicit-from-inequality',
    (db) => col(db).where('rating', WhereFilter.greaterThan, 4),
  );
  query(
    'order-by/implicit-from-inequalities',
    (db) => col(db)
        .where('rating', WhereFilter.greaterThan, 4)
        .where('published', WhereFilter.lessThan, 2000),
  );
  query(
    'order-by/explicit-and-inequality',
    (db) => col(db)
        .where('rating', WhereFilter.greaterThan, 4)
        .orderBy('title', descending: true),
  );

  query('limit/with-order-by', (db) => col(db).orderBy('rating').limit(5));
  query('limit/without-order-by', (db) => col(db).limit(5));
  query(
    'limit-to-last/plain',
    (db) => col(db).orderBy('rating').limitToLast(5),
  );
  query('offset/plain', (db) => col(db).offset(10));
  query(
    'offset/with-limit',
    (db) => col(db).orderBy('rating').limit(5).offset(10),
  );

  query('cursor/start-at', (db) => col(db).orderBy('rating').startAt([4]));
  query(
    'cursor/start-after',
    (db) => col(db).orderBy('rating').startAfter([4]),
  );
  query('cursor/end-at', (db) => col(db).orderBy('rating').endAt([4]));
  query('cursor/end-before', (db) => col(db).orderBy('rating').endBefore([4]));
  query(
    'cursor/multiple-fields',
    (db) => col(db).orderBy('rating').orderBy('title').startAt([4, 'M']),
  );
  query(
    'cursor/start-and-end',
    (db) => col(db).orderBy('rating').startAfter([2]).endAt([4]),
  );
  query(
    'cursor/limit-to-last',
    (db) =>
        col(db).orderBy('rating').startAt([2]).endBefore([5]).limitToLast(3),
  );

  query(
    'select/fields',
    (db) => col(db).select([
      FieldPath(const ['title']),
      FieldPath(const ['author']),
    ]),
  );
  query('select/empty', (db) => col(db).select());

  VectorQuery<DocumentData> nearest(
    Query<DocumentData> base, {
    Object queryVector = const [0.1, 0.2, 0.3],
    DistanceMeasure distanceMeasure = DistanceMeasure.euclidean,
    String? distanceResultField,
    double? distanceThreshold,
  }) {
    return base.findNearest(
      vectorField: 'embedding',
      queryVector: queryVector,
      limit: 5,
      distanceMeasure: distanceMeasure,
      distanceResultField: distanceResultField,
      distanceThreshold: distanceThreshold,
    );
  }

  query('vector/euclidean', (db) => nearest(col(db)));
  query(
    'vector/cosine',
    (db) => nearest(col(db), distanceMeasure: DistanceMeasure.cosine),
  );
  query(
    'vector/dot-product',
    (db) => nearest(col(db), distanceMeasure: DistanceMeasure.dotProduct),
  );
  query('vector/vector-value', (db) => nearest(col(db), queryVector: _vector));
  query(
    'vector/with-prefilter',
    (db) => nearest(col(db).where('genre', WhereFilter.equal, 'Fantasy')),
  );
  query(
    'vector/distance-result-field',
    (db) => nearest(col(db), distanceResultField: 'distance'),
  );
  query(
    'vector/distance-threshold',
    (db) => nearest(col(db), distanceThreshold: 0.5),
  );
}

// -----------------------------------------------------------------------------
// Stages and execute options
// -----------------------------------------------------------------------------

void _registerStages(_Registry r) {
  void stage(String id, _Build build, [List<_Build> alternatives = const []]) {
    r.pipeline('stages/$id', build, alternatives);
  }

  stage(
    'where/condition',
    (db) => _books(db).where(field('rating').greaterThan(4)),
  );
  stage(
    'where/chained',
    (db) => _books(db)
        .where(field('rating').greaterThan(4))
        .where(field('genre').equal('Fantasy')),
  );
  stage(
    'where/raw-options',
    (db) => _books(db).where(
      field('rating').greaterThan(4),
      rawOptions: const {'foo': 'bar', 'outer.inner': true},
    ),
  );

  stage('select/field-names', (db) => _books(db).select(['title', 'author']));
  stage(
    'select/fields',
    (db) => _books(db).select([field('title'), field('author')]),
  );
  stage(
    'select/aliased',
    (db) => _books(db).select([
      field('title').as('name'),
      field('rating').multiply(2).as('doubled'),
    ]),
  );
  stage(
    'select/mixed',
    (db) => _books(
      db,
    ).select(['title', field('author'), field('rating').as('score')]),
  );
  stage(
    'select/nested-field-path',
    (db) => _books(db).select(['metadata.lang', field('awards.hugo')]),
  );
  stage(
    'select/special-characters',
    (db) => _books(db).select(['first-name', field('last name')]),
  );
  stage(
    'select/options-object',
    (db) => _books(db).select(['title', field('rating').as('score')]),
  );
  stage(
    'select/raw-options',
    (db) => _books(db).select(['title'], rawOptions: const {'foo': 'bar'}),
  );

  stage(
    'add-fields/single',
    (db) => _books(db).addFields([field('rating').as('copiedRating')]),
  );
  stage(
    'add-fields/multiple',
    (db) => _books(db).addFields([
      field('rating').as('copiedRating'),
      constant(true).as('annotated'),
    ]),
  );
  // Dart's addFields only takes aliased expressions; a field aliased to its
  // own name is what Node sends for a bare field.
  stage(
    'add-fields/field',
    (db) => _books(db).addFields([field('rating').as('rating')]),
  );
  stage(
    'add-fields/raw-options',
    (db) => _books(db).addFields(
      [field('rating').as('copiedRating')],
      rawOptions: const {'foo': 'bar'},
    ),
  );

  stage(
    'remove-fields/field-names',
    (db) => _books(db).removeFields(['title', 'author']),
  );
  stage(
    'remove-fields/fields',
    (db) => _books(db).removeFields([field('title'), field('author')]),
  );
  stage(
    'remove-fields/nested',
    (db) => _books(db).removeFields(['metadata.lang']),
  );
  stage(
    'remove-fields/raw-options',
    (db) =>
        _books(db).removeFields(['title'], rawOptions: const {'foo': 'bar'}),
  );

  stage(
    'sort/ascending-method',
    (db) => _books(db).sort([field('rating').ascending()]),
  );
  stage(
    'sort/descending-method',
    (db) => _books(db).sort([field('rating').descending()]),
  );
  stage(
    'sort/multiple',
    (db) => _books(
      db,
    ).sort([field('rating').descending(), field('title').ascending()]),
  );
  stage(
    'sort/top-level-field-name',
    (db) => _books(db).sort([ascending('rating'), descending('title')]),
  );
  stage(
    'sort/top-level-expression',
    (db) => _books(db).sort([
      ascending(field('rating')),
      descending(field('title').charLength()),
    ]),
  );
  stage(
    'sort/expression-method',
    (db) => _books(db).sort([field('title').charLength().descending()]),
  );
  stage(
    'sort/raw-options',
    (db) => _books(
      db,
    ).sort([field('rating').descending()], rawOptions: const {'foo': 'bar'}),
  );

  stage('offset/plain', (db) => _books(db).offset(10));
  stage(
    'offset/raw-options',
    (db) => _books(db).offset(10, rawOptions: const {'foo': 'bar'}),
  );
  stage('limit/plain', (db) => _books(db).limit(10));
  stage('limit/zero', (db) => _books(db).limit(0));
  stage(
    'limit/raw-options',
    (db) => _books(db).limit(10, rawOptions: const {'foo': 'bar'}),
  );

  stage(
    'distinct/field-names',
    (db) => _books(db).distinct(['genre', 'author']),
  );
  stage('distinct/fields', (db) => _books(db).distinct([field('genre')]));
  stage(
    'distinct/aliased',
    (db) =>
        _books(db).distinct([field('genre').toLowerCase().as('lowerGenre')]),
  );
  stage(
    'distinct/raw-options',
    (db) => _books(db).distinct(['genre'], rawOptions: const {'foo': 'bar'}),
  );

  stage(
    'aggregate/single',
    (db) => _books(db).aggregate([PipelineFunctions.countAll().as('total')]),
  );
  stage(
    'aggregate/multiple',
    (db) => _books(db).aggregate([
      PipelineFunctions.countAll().as('total'),
      PipelineFunctions.average('rating').as('averageRating'),
    ]),
  );
  stage(
    'aggregate/groups-field-names',
    (db) => _books(
      db,
    ).aggregate([PipelineFunctions.countAll().as('total')], groups: ['genre']),
  );
  stage(
    'aggregate/groups-mixed',
    (db) => _books(db).aggregate(
      [
        PipelineFunctions.countAll().as('total'),
        PipelineFunctions.maximum('rating').as('best'),
      ],
      groups: [
        'genre',
        field('author'),
        field('published').divide(10).floor().as('decade'),
      ],
    ),
  );
  stage(
    'aggregate/raw-options',
    (db) => _books(db).aggregate(
      [PipelineFunctions.countAll().as('total')],
      groups: ['genre'],
      rawOptions: const {'foo': 'bar'},
    ),
  );

  Pipeline findNearest(
    Firestore db, {
    Object vectorField = 'embedding',
    Object queryVector = const [0.1, 0.2, 0.3],
    DistanceMeasure distanceMeasure = DistanceMeasure.euclidean,
    int? limit,
    String? distanceResultField,
    Map<String, Object?> rawOptions = const {},
  }) {
    return _books(db).findNearest(
      vectorField: vectorField,
      queryVector: queryVector,
      distanceMeasure: distanceMeasure,
      limit: limit,
      distanceResultField: distanceResultField,
      rawOptions: rawOptions,
    );
  }

  stage('find-nearest/number-array', findNearest);
  stage(
    'find-nearest/integer-array',
    (db) => findNearest(db, queryVector: const [1, 2, 3]),
  );
  stage(
    'find-nearest/vector-value',
    (db) => findNearest(db, queryVector: _vector),
  );
  stage(
    'find-nearest/field',
    (db) => findNearest(db, vectorField: field('embedding')),
  );
  stage(
    'find-nearest/cosine',
    (db) => findNearest(db, distanceMeasure: DistanceMeasure.cosine),
  );
  stage(
    'find-nearest/dot-product',
    (db) => findNearest(db, distanceMeasure: DistanceMeasure.dotProduct),
  );
  stage('find-nearest/limit', (db) => findNearest(db, limit: 10));
  stage(
    'find-nearest/distance-field',
    (db) => findNearest(db, distanceResultField: 'distance'),
  );
  stage(
    'find-nearest/all-options',
    (db) => findNearest(db, limit: 10, distanceResultField: 'distance'),
  );
  stage(
    'find-nearest/raw-options',
    (db) => findNearest(
      db,
      limit: 10,
      distanceResultField: 'distance',
      rawOptions: const {'limit': 20, 'extra.flag': true},
    ),
  );

  stage('replace-with/field-name', (db) => _books(db).replaceWith('metadata'));
  stage(
    'replace-with/field',
    (db) => _books(db).replaceWith(field('metadata')),
  );
  stage(
    'replace-with/map-expression',
    (db) => _books(db).replaceWith(
      PipelineFunctions.map([
        'title',
        field('title'),
        'rating',
        field('rating'),
      ]),
    ),
  );
  stage(
    'replace-with/raw-options',
    (db) =>
        _books(db).replaceWith('metadata', rawOptions: const {'foo': 'bar'}),
  );

  stage('sample/documents', (db) => _books(db).sample(documents: 10));
  stage('sample/documents-option', (db) => _books(db).sample(documents: 10));
  stage('sample/percentage', (db) => _books(db).sample(percentage: 0.25));
  stage(
    'sample/raw-options',
    (db) => _books(db).sample(documents: 10, rawOptions: const {'foo': 'bar'}),
  );

  stage(
    'union/plain',
    (db) => _books(db).union(db.pipeline().collection('magazines')),
  );
  stage(
    'union/complex',
    (db) => _books(db)
        .select(['title'])
        .union(
          db
              .pipeline()
              .collectionGroup('reviews')
              .where(field('rating').greaterThan(3))
              .select(['title']),
        ),
  );
  stage(
    'union/raw-options',
    (db) => _books(db).union(
      db.pipeline().collection('magazines'),
      rawOptions: const {'foo': 'bar'},
    ),
  );

  stage('unnest/field', (db) => _books(db).unnest(field('tags')), [
    (db) => _books(db).unnest('tags'),
  ]);
  stage(
    'unnest/aliased-field',
    (db) => _books(db).unnest(field('tags').as('tag')),
  );
  stage(
    'unnest/index-field',
    (db) => _books(db).unnest(field('tags').as('tag'), indexField: 'index'),
  );
  stage(
    'unnest/expression',
    (db) => _books(
      db,
    ).unnest(PipelineFunctions.array([1, 2, field('rating')]).as('item')),
  );
  stage(
    'unnest/options-object',
    (db) => _books(db).unnest(field('tags').as('tag'), indexField: 'idx'),
  );
  stage(
    'unnest/raw-options',
    (db) => _books(db).unnest(
      field('tags').as('tag'),
      indexField: 'idx',
      rawOptions: {'index_field': field('position'), 'foo': 'bar'},
    ),
  );

  stage(
    'raw-stage/expression-params',
    (db) => _books(db).rawStage('where', [field('rating').greaterThan(4)]),
  );
  stage('raw-stage/literal-params', (db) => _books(db).rawStage('limit', [10]));
  stage(
    'raw-stage/string-params',
    (db) => _books(db).rawStage('custom', ['a', 1.5, true, null]),
  );
  stage(
    'raw-stage/plain-object-param',
    (db) => _books(db).rawStage('select', [
      {'title': field('title'), 'one': 1},
    ]),
  );
  stage(
    'raw-stage/nested-plain-object-param',
    (db) => _books(db).rawStage('select', [
      {
        'meta': {'lang': field('lang')},
      },
    ]),
  );
  // A map param is a literal map whose values are converted like a value
  // position: a nested map or list becomes a map(...) or array(...) function,
  // with or without expressions in it.
  stage(
    'raw-stage/plain-object-param-literals',
    (db) => _books(db).rawStage('custom', [
      {'a': 1, 'b': 'x', 'c': null},
    ]),
  );
  stage(
    'raw-stage/empty-object-param',
    (db) => _books(db).rawStage('custom', [<String, Object?>{}]),
  );
  stage(
    'raw-stage/nested-plain-object-param-literals',
    (db) => _books(db).rawStage('custom', [
      {
        'meta': {'lang': 'en', 'year': 2020},
      },
    ]),
  );
  stage(
    'raw-stage/nested-empty-object-param',
    (db) => _books(db).rawStage('custom', [
      {'meta': <String, Object?>{}},
    ]),
  );
  stage(
    'raw-stage/array-in-object-param',
    (db) => _books(db).rawStage('custom', [
      {
        'tags': [field('genre'), 'classic'],
      },
    ]),
  );
  stage(
    'raw-stage/array-in-object-param-literals',
    (db) => _books(db).rawStage('custom', [
      {
        'tags': [1, 2],
      },
    ]),
  );
  stage(
    'raw-stage/deeply-nested-object-param',
    (db) => _books(db).rawStage('custom', [
      {
        'a': {
          'b': {'c': field('x')},
          'd': [
            field('y'),
            {'e': 1},
          ],
        },
      },
    ]),
  );
  // constant() keeps a nested map literal.
  stage(
    'raw-stage/constant-in-object-param',
    (db) => _books(db).rawStage('custom', [
      {
        'meta': constant({'lang': 'en'}),
      },
    ]),
  );
  stage(
    'raw-stage/array-param',
    (db) => _books(db).rawStage('custom', [
      [1, 'a', field('title')],
    ]),
  );
  // Any other param, a list included, is sent as is: a literal value all the
  // way down.
  stage(
    'raw-stage/array-param-literals',
    (db) => _books(db).rawStage('custom', [
      [1, 2, 3],
    ]),
  );
  stage(
    'raw-stage/nested-array-param',
    (db) => _books(db).rawStage('custom', [
      [
        1,
        [2, field('x')],
      ],
    ]),
  );
  stage(
    'raw-stage/object-in-array-param',
    (db) => _books(db).rawStage('custom', [
      [
        {
          'a': field('x'),
          'b': {'c': 1},
        },
      ],
    ]),
  );
  stage(
    'raw-stage/aggregate-params',
    (db) => _books(db).rawStage('aggregate', [
      {
        'total': PipelineFunctions.countAll(),
        'best': PipelineFunctions.maximum('rating'),
      },
      {'genre': field('genre')},
    ]),
  );
  stage(
    'raw-stage/options',
    (db) => _books(db).rawStage(
      'find_nearest',
      [field('embedding'), _vector, 'euclidean'],
      options: {'limit': 10, 'distance_field': field('distance')},
    ),
  );
  stage(
    'raw-stage/options-dot-notation',
    (db) =>
        _books(db).rawStage('custom', [], options: {'outer.inner': 'value'}),
  );
  void rawOptions(String id, Map<String, Object?> options) {
    stage(
      'raw-stage/$id',
      (db) => _books(db).rawStage('custom', const [], options: options),
    );
  }

  rawOptions('options-nested-object', {
    'outer': {'inner': 'value', 'n': 1},
  });
  rawOptions('options-expression-values', {
    'target': field('x'),
    'nested': {'target': field('y')},
  });
  rawOptions('options-dot-notation-siblings', {'outer.a': 1, 'outer.b': 2});
  rawOptions('options-dot-notation-deep', {'a.b.c': true});
  // Keys apply in order: a dotted key merges into an earlier map, a map
  // replaces what earlier dotted keys built, and a dotted key replaces an
  // earlier value that is not a map.
  rawOptions('options-dot-notation-merges-object', {
    'outer': {'a': 1},
    'outer.b': 2,
  });
  rawOptions('options-object-replaces-dot-notation', {
    'outer.a': 1,
    'outer': {'b': 2},
  });
  rawOptions('options-dot-notation-replaces-scalar', {
    'outer': 'x',
    'outer.a': 1,
  });
  // Segments are not unescaped: backticks are part of the name.
  rawOptions('options-dot-notation-backticks', {'a.`b.c`': 1});

  // Dart's search stage takes the backend options as-is.
  final breakfast = documentMatches('breakfast');
  stage('search/query-string', (db) => _books(db).search({'query': breakfast}));
  stage(
    'search/query-expression',
    (db) => _books(db).search({'query': breakfast}),
  );
  stage(
    'search/limit-offset',
    (db) => _books(db).search({'query': breakfast, 'limit': 10, 'offset': 5}),
  );
  stage(
    'search/retrieval-depth-language',
    (db) => _books(db).search({
      'query': breakfast,
      'retrieval_depth': 100,
      'language_code': 'en',
    }),
  );
  stage(
    'search/sort-single',
    (db) => _books(db).search({
      'query': breakfast,
      'sort': [score().descending()],
    }),
  );
  stage(
    'search/sort-list',
    (db) => _books(db).search({
      'query': breakfast,
      'sort': [score().descending(), field('title').ascending()],
    }),
  );
  stage(
    'search/add-fields',
    (db) => _books(db).search({
      'query': breakfast,
      'add_fields': {'searchScore': score()},
    }),
  );
  stage(
    'search/raw-options',
    (db) => _books(db).search(
      {'query': breakfast, 'limit': 10},
      rawOptions: const {'limit': 20, 'extra.flag': true},
    ),
  );
}

void _registerOptions(_Registry r) {
  void execute(
    String id,
    Future<PipelineSnapshot> Function(Pipeline pipeline) run,
  ) {
    r.run('options/$id', [(db) => run(_books(db))]);
  }

  const analyze = PipelineExplainMode.analyze;
  const text = PipelineExplainOutputFormat.text;

  execute('none/plain', (p) => p.execute());
  execute('none/empty-object', (p) => p.execute());
  execute(
    'index-mode/recommended',
    (p) => p.execute(indexMode: PipelineIndexMode.recommended),
  );
  execute(
    'explain/mode-analyze',
    (p) => p.execute(explain: const PipelineExplainOptions(mode: analyze)),
  );
  execute(
    'explain/mode-execute',
    (p) => p.execute(
      explain: const PipelineExplainOptions(mode: PipelineExplainMode.execute),
    ),
  );
  execute(
    'explain/output-format-text',
    (p) => p.execute(explain: const PipelineExplainOptions(outputFormat: text)),
  );
  execute(
    'explain/mode-and-output-format',
    (p) => p.execute(
      explain: const PipelineExplainOptions(mode: analyze, outputFormat: text),
    ),
  );
  execute(
    'explain/empty',
    (p) => p.execute(explain: const PipelineExplainOptions()),
  );
  execute(
    'combined/index-mode-and-explain',
    (p) => p.execute(
      indexMode: PipelineIndexMode.recommended,
      explain: const PipelineExplainOptions(mode: analyze, outputFormat: text),
    ),
  );
  execute(
    'raw-options/flat',
    (p) => p.execute(rawOptions: {'foo': 'bar', 'count': 3}),
  );
  execute(
    'raw-options/nested-object',
    (p) => p.execute(
      rawOptions: {
        'explain_options': {'mode': 'analyze'},
      },
    ),
  );
  execute(
    'raw-options/dot-notation',
    (p) => p.execute(rawOptions: {'explain_options.mode': 'analyze'}),
  );
  execute(
    'raw-options/override-known',
    (p) => p.execute(
      indexMode: PipelineIndexMode.recommended,
      rawOptions: {'index_mode': 'custom'},
    ),
  );
  execute(
    'raw-options/merge-into-explain',
    (p) => p.execute(
      explain: const PipelineExplainOptions(mode: analyze),
      rawOptions: {'explain_options.output_format': 'text'},
    ),
  );
  execute(
    'raw-options/dot-notation-overrides-known',
    (p) => p.execute(
      explain: const PipelineExplainOptions(mode: analyze, outputFormat: text),
      rawOptions: {'explain_options.mode': 'execute'},
    ),
  );
  execute(
    'raw-options/object-replaces-known',
    (p) => p.execute(
      explain: const PipelineExplainOptions(mode: analyze, outputFormat: text),
      rawOptions: {
        'explain_options': {'mode': 'execute'},
      },
    ),
  );
  execute(
    'raw-options/dot-notation-into-empty-explain',
    (p) => p.execute(
      explain: const PipelineExplainOptions(),
      rawOptions: {'explain_options.mode': 'analyze'},
    ),
  );
  execute(
    'raw-options/dot-notation-replaces-known-scalar',
    (p) => p.execute(
      indexMode: PipelineIndexMode.recommended,
      rawOptions: {'index_mode.mode': 'custom'},
    ),
  );
  execute(
    'raw-options/dot-notation-siblings',
    (p) => p.execute(rawOptions: {'outer.a': 1, 'outer.b': 'two'}),
  );
  execute(
    'raw-options/dot-notation-deep',
    (p) => p.execute(rawOptions: {'a.b.c': true}),
  );
}

// -----------------------------------------------------------------------------
// Values
// -----------------------------------------------------------------------------

void _registerValues(_Registry r) {
  void selectConstant(String id, Object? value, [List<_Expr> alts = const []]) {
    r.expr('values/constant/$id', () => constant(value), alts);
  }

  selectConstant('integer', 42);
  selectConstant('negative-integer', -7);
  selectConstant('zero', 0);
  selectConstant('double', 3.14);
  selectConstant('nan', double.nan);
  selectConstant('infinity', double.infinity);
  selectConstant('negative-infinity', double.negativeInfinity);
  selectConstant('string', 'Fantasy');
  selectConstant('empty-string', '');
  selectConstant('true', true);
  selectConstant('false', false);
  selectConstant('null', null);
  selectConstant('timestamp', _timestamp);
  selectConstant(
    'timestamp-millis',
    Timestamp(seconds: 1700000000, nanoseconds: 123000000),
  );
  selectConstant('date', _date);
  selectConstant('geo-point', _geoPoint);
  selectConstant('bytes', _bytes);
  r.dbExpr('values/constant/document-reference', (db) => constant(_docRef(db)));
  selectConstant('vector', _vector, [
    () => Expression.vector([0.1, 0.2, 0.3]),
  ]);
  selectConstant('array', [1, 'a', true, null]);
  selectConstant('map', {
    'a': 1,
    'b': 'x',
    'nested': {
      'c': [1, 2],
    },
  });

  void selectField(String id, String name) {
    r.expr('values/field/$id', () => field(name), [
      () => Expression.field(name),
    ]);
  }

  selectField('simple', 'title');
  selectField('nested', 'metadata.lang');
  selectField('document-id', '__name__');
  selectField('special-characters', 'first-name');
  selectField('space', 'last name');
  selectField('non-ascii', 'naïve');

  r.expr('values/variable/plain', () => variable('x'), [
    () => Expression.variable('x'),
  ]);

  void equalValue(String id, Object? Function() value) {
    r.expr('values/value-position/$id', () => field('value').equal(value()));
  }

  equalValue('integer', () => 1);
  equalValue('double', () => 1.5);
  equalValue('string', () => 'a');
  equalValue('boolean', () => true);
  equalValue('null', () => null);
  equalValue('timestamp', () => _timestamp);
  equalValue('date', () => _date);
  equalValue('geo-point', () => _geoPoint);
  equalValue('bytes', () => _bytes);
  r.dbExpr(
    'values/value-position/document-reference',
    (db) => field('value').equal(_docRef(db)),
  );
  equalValue('vector', () => _vector);
  equalValue('list-plain', () => ['a', 'b']);
  equalValue('list-with-expression', () => ['a', field('b')]);
  equalValue(
    'list-nested',
    () => [
      ['a'],
      {'k': 'v'},
    ],
  );
  equalValue('list-empty', () => <Object?>[]);
  equalValue('map-plain', () => {'a': 1, 'b': 'x'});
  equalValue('map-with-expression', () => {'a': field('x'), 'b': 1});
  equalValue(
    'map-nested',
    () => {
      'inner': {'k': field('y')},
      'list': [field('z')],
    },
  );
  equalValue('map-empty', () => <String, Object?>{});
  equalValue('constant-list', () => constant(['a', 'b']));

  r.pipeline('values/data-types/all-constants', (db) {
    final docRef = _docRef(db);
    return _books(db).limit(1).select([
      constant(1).as('number'),
      constant('a string').as('string'),
      constant(true).as('boolean'),
      constant(null).as('null'),
      constant(_geoPoint).as('geoPoint'),
      constant(_timestamp).as('timestamp'),
      constant(_date).as('date'),
      constant(_bytes).as('bytes'),
      constant(docRef).as('documentReference'),
      constant(_vector).as('vectorValue'),
      PipelineFunctions.map([
        'number',
        1,
        'string',
        'a string',
        'boolean',
        true,
        'null',
        null,
        'geoPoint',
        _geoPoint,
        'timestamp',
        _timestamp,
        'date',
        _date,
        'uint8Array',
        _bytes,
        'documentReference',
        docRef,
        'vectorValue',
        _vector,
        'map',
        {'number': 2, 'string': 'b string'},
        'array',
        [1, 'c string'],
      ]).as('map'),
      PipelineFunctions.array([
        1,
        'a string',
        true,
        null,
        _geoPoint,
        _timestamp,
        _date,
        _bytes,
        docRef,
        _vector,
        {'number': 2, 'string': 'b string'},
      ]).as('array'),
    ]);
  });

  r.pipeline('values/data-types/array-and-map-functions', (db) {
    List<Object?> metadataArray() => [
      1,
      2,
      field('genre'),
      PipelineFunctions.multiply('rating', 10),
      [field('title')],
      {'published': field('published')},
    ];
    Map<String, Object?> metadata() => {
      'genre': field('genre'),
      'rating': PipelineFunctions.multiply('rating', 10),
      'nestedArray': [field('title')],
      'nestedMap': {'published': field('published')},
    };

    return _books(db)
        .sort([field('rating').descending()])
        .limit(1)
        .select(['title', 'author', 'genre', 'rating', 'published', 'tags'])
        .addFields([
          PipelineFunctions.array(metadataArray()).as('metadataArray'),
          PipelineFunctions.map([
            for (final MapEntry(:key, :value) in metadata().entries) ...[
              key,
              value,
            ],
          ]).as('metadata'),
        ])
        .where(
          and([
            PipelineFunctions.equal('metadataArray', metadataArray()),
            PipelineFunctions.equal('metadata', metadata()),
          ]),
        );
  });
}

// -----------------------------------------------------------------------------
// Functions
// -----------------------------------------------------------------------------

void _registerArithmetic(_Registry r) {
  r.binary(
    'add',
    'rating',
    1,
    () => field('bonus'),
    PipelineFunctions.add,
    (e, v) => e.add(v),
  );
  r.expr('functions/add/method-double', () => field('rating').add(0.5));
  r.binary(
    'subtract',
    'rating',
    1,
    () => field('penalty'),
    PipelineFunctions.subtract,
    (e, v) => e.subtract(v),
  );
  r.binary(
    'multiply',
    'rating',
    2,
    () => field('weight'),
    PipelineFunctions.multiply,
    (e, v) => e.multiply(v),
  );
  r.binary(
    'divide',
    'rating',
    2,
    () => field('count'),
    PipelineFunctions.divide,
    (e, v) => e.divide(v),
  );
  r.binary(
    'mod',
    'rating',
    2,
    () => field('divisor'),
    PipelineFunctions.mod,
    (e, v) => e.mod(v),
  );
  r.binary(
    'pow',
    'rating',
    2,
    () => field('exponent'),
    PipelineFunctions.pow,
    (e, v) => e.pow(v),
  );

  r.unary('abs', 'rating', PipelineFunctions.abs, (e) => e.abs());
  r.unary('ceil', 'rating', PipelineFunctions.ceil, (e) => e.ceil());
  r.unary('floor', 'rating', PipelineFunctions.floor, (e) => e.floor());
  r.unary('exp', 'rating', PipelineFunctions.exp, (e) => e.exp());
  r.unary('ln', 'rating', PipelineFunctions.ln, (e) => e.ln());
  r.unary('sqrt', 'rating', PipelineFunctions.sqrt, (e) => e.sqrt());
  r.unary('log10', 'rating', PipelineFunctions.log10, (e) => e.log10());

  for (final (name, static, method) in [
    (
      'round',
      PipelineFunctions.round,
      (PipelineExpression e, [Object? places]) => e.round(places),
    ),
    (
      'trunc',
      PipelineFunctions.trunc,
      (PipelineExpression e, [Object? places]) => e.trunc(places),
    ),
  ]) {
    r.unary(name, 'rating', static, method);
    r.expr(
      'functions/$name/static-field-name-places-literal',
      () => static('rating', 2),
    );
    r.expr(
      'functions/$name/static-expression-places-expression',
      () => static(field('rating'), field('places')),
    );
    r.expr(
      'functions/$name/method-places-literal',
      () => method(field('rating'), 2),
    );
    r.expr(
      'functions/$name/method-places-expression',
      () => method(field('rating'), field('places')),
    );
  }

  r.expr('functions/rand/static', PipelineFunctions.rand);
}

void _registerComparisonAndLogic(_Registry r) {
  for (final (name, static, topLevel, method)
      in <(String, _Static2, _Static2, _Method1)>[
        ('equal', PipelineFunctions.equal, equal, (e, v) => e.equal(v)),
        (
          'notEqual',
          PipelineFunctions.notEqual,
          notEqual,
          (e, v) => e.notEqual(v),
        ),
        (
          'lessThan',
          PipelineFunctions.lessThan,
          lessThan,
          (e, v) => e.lessThan(v),
        ),
        (
          'lessThanOrEqual',
          PipelineFunctions.lessThanOrEqual,
          lessThanOrEqual,
          (e, v) => e.lessThanOrEqual(v),
        ),
        (
          'greaterThan',
          PipelineFunctions.greaterThan,
          greaterThan,
          (e, v) => e.greaterThan(v),
        ),
        (
          'greaterThanOrEqual',
          PipelineFunctions.greaterThanOrEqual,
          greaterThanOrEqual,
          (e, v) => e.greaterThanOrEqual(v),
        ),
      ]) {
    r.binary(
      name,
      'rating',
      4,
      () => field('threshold'),
      static,
      method,
      staticAlternatives: [topLevel],
    );
    r.expr(
      'functions/$name/static-field-name-string',
      () => static('genre', 'Fantasy'),
      [() => topLevel('genre', 'Fantasy')],
    );
  }

  r.expr(
    'functions/and/static-two',
    () => PipelineFunctions.and([_isFantasy(), _isGood()]),
    [
      () => and([_isFantasy(), _isGood()]),
    ],
  );
  r.expr(
    'functions/and/static-three',
    () => PipelineFunctions.and([_isFantasy(), _isGood(), _isOld()]),
    [
      () => and([_isFantasy(), _isGood(), _isOld()]),
    ],
  );
  r.expr(
    'functions/or/static-two',
    () => PipelineFunctions.or([_isFantasy(), _isGood()]),
    [
      () => or([_isFantasy(), _isGood()]),
    ],
  );
  r.expr(
    'functions/or/static-three',
    () => PipelineFunctions.or([_isFantasy(), _isGood(), _isOld()]),
    [
      () => or([_isFantasy(), _isGood(), _isOld()]),
    ],
  );
  r.expr(
    'functions/xor/static-two',
    () => PipelineFunctions.xor([_isFantasy(), _isGood()]),
  );
  r.expr(
    'functions/xor/static-three',
    () => PipelineFunctions.xor([_isFantasy(), _isGood(), _isOld()]),
  );
  r.expr(
    'functions/nor/static-two',
    () => PipelineFunctions.nor([_isFantasy(), _isGood()]),
  );
  r.expr(
    'functions/nor/static-three',
    () => PipelineFunctions.nor([_isFantasy(), _isGood(), _isOld()]),
  );
  r.expr('functions/not/static', () => PipelineFunctions.not(_isFantasy()), [
    () => not(_isFantasy()),
  ]);
  r.expr('functions/not/method', () => _isFantasy().not());
  r.expr(
    'functions/conditional/static',
    () => PipelineFunctions.conditional(
      _isGood(),
      field('title'),
      constant('n/a'),
    ),
  );
  r.expr(
    'functions/conditional/method',
    () => _isGood().conditional(field('title'), constant('n/a')),
  );
  r.expr(
    'functions/switchOn/static-pair',
    () => PipelineFunctions.switchOn([_isGood(), constant('good')]),
  );
  r.expr(
    'functions/switchOn/static-pairs-and-default',
    () => PipelineFunctions.switchOn([
      _isGood(),
      constant('good'),
      _isOld(),
      constant('old'),
      constant('other'),
    ]),
  );

  r.expr(
    'functions/logicalMaximum/static-field-name-literal',
    () => PipelineFunctions.logicalMaximum('rating', 1),
  );
  r.expr(
    'functions/logicalMaximum/static-expression-variadic',
    () =>
        PipelineFunctions.logicalMaximum(field('rating'), field('floor'), [3]),
  );
  r.expr(
    'functions/logicalMaximum/method-literal',
    () => field('rating').logicalMaximum(1),
  );
  r.expr(
    'functions/logicalMaximum/method-variadic',
    () => field('rating').logicalMaximum(field('floor'), [3]),
  );
  r.expr(
    'functions/logicalMinimum/static-field-name-literal',
    () => PipelineFunctions.logicalMinimum('rating', 5),
  );
  r.expr(
    'functions/logicalMinimum/static-expression-variadic',
    () => PipelineFunctions.logicalMinimum(field('rating'), field('ceiling'), [
      3,
    ]),
  );
  r.expr(
    'functions/logicalMinimum/method-literal',
    () => field('rating').logicalMinimum(5),
  );
  r.expr(
    'functions/logicalMinimum/method-variadic',
    () => field('rating').logicalMinimum(field('ceiling'), [3]),
  );

  r.unary('exists', 'title', PipelineFunctions.exists, (e) => e.exists());
  r.unary('isAbsent', 'title', PipelineFunctions.isAbsent, (e) => e.isAbsent());
  r.binary(
    'ifAbsent',
    'nickname',
    'anonymous',
    () => field('name'),
    PipelineFunctions.ifAbsent,
    (e, v) => e.ifAbsent(v),
  );
  r.binary(
    'ifNull',
    'nickname',
    'anonymous',
    () => field('name'),
    PipelineFunctions.ifNull,
    (e, v) => e.ifNull(v),
  );

  PipelineExpression failing() => field('rating').divide(0);
  r.expr(
    'functions/isError/static-expression',
    () => PipelineFunctions.isError(failing()),
  );
  r.expr('functions/isError/method', () => failing().isError());
  r.expr(
    'functions/ifError/static-expression-literal',
    () => PipelineFunctions.ifError(failing(), 0),
  );
  r.expr(
    'functions/ifError/static-expression-expression',
    () => PipelineFunctions.ifError(failing(), field('fallback')),
  );
  // Node types ifError of two booleans as a boolean, hence the where stage.
  r.expr(
    'functions/ifError/static-boolean-boolean',
    () => PipelineFunctions.ifError(_isGood(), constant(false)).asBoolean(),
  );
  r.expr('functions/ifError/method-literal', () => failing().ifError(0));
  r.expr(
    'functions/ifError/method-expression',
    () => failing().ifError(field('fallback')),
  );
  r.expr(
    'functions/ifError/method-boolean-boolean',
    () => _isGood().ifError(constant(false)).asBoolean(),
  );
  r.expr(
    'functions/ifError/method-boolean-literal',
    () => _isGood().ifError(false).asBoolean(),
  );

  r.expr(
    'functions/coalesce/static-field-name-literal',
    () => PipelineFunctions.coalesce('nickname', 'anonymous'),
  );
  r.expr(
    'functions/coalesce/static-expression-variadic',
    () => PipelineFunctions.coalesce(field('nickname'), field('name'), [
      'anonymous',
    ]),
  );
  r.expr(
    'functions/coalesce/method-literal',
    () => field('nickname').coalesce('anonymous'),
  );
  r.expr(
    'functions/coalesce/method-variadic',
    () => field('nickname').coalesce(field('name'), ['anonymous']),
  );
}

void _registerStrings(_Registry r) {
  r.unary(
    'charLength',
    'title',
    PipelineFunctions.charLength,
    (e) => e.charLength(),
  );
  r.unary(
    'byteLength',
    'title',
    PipelineFunctions.byteLength,
    (e) => e.byteLength(),
  );
  r.unary(
    'toLower',
    'title',
    PipelineFunctions.toLower,
    (e) => e.toLowerCase(),
  );
  r.unary(
    'toUpper',
    'title',
    PipelineFunctions.toUpper,
    (e) => e.toUpperCase(),
  );
  r.unary(
    'stringReverse',
    'title',
    PipelineFunctions.stringReverse,
    (e) => e.stringReverse(),
  );
  r.unary('reverse', 'title', PipelineFunctions.reverse, (e) => e.reverse());
  r.unary('length', 'title', PipelineFunctions.length, (e) => e.length());

  r.binary(
    'like',
    'title',
    'The%',
    () => field('pattern'),
    PipelineFunctions.like,
    (e, v) => e.like(v),
  );
  r.binary(
    'regexContains',
    'title',
    'Lord',
    () => field('pattern'),
    PipelineFunctions.regexContains,
    (e, v) => e.regexContains(v),
  );
  r.binary(
    'regexMatch',
    'title',
    '^The.*',
    () => field('pattern'),
    PipelineFunctions.regexMatch,
    (e, v) => e.regexMatch(v),
  );
  r.binary(
    'regexFind',
    'title',
    r'[A-Z]\w+',
    () => field('pattern'),
    PipelineFunctions.regexFind,
    (e, v) => e.regexFind(v),
  );
  r.binary(
    'regexFindAll',
    'title',
    r'[A-Z]\w+',
    () => field('pattern'),
    PipelineFunctions.regexFindAll,
    (e, v) => e.regexFindAll(v),
  );
  r.binary(
    'stringContains',
    'title',
    'Ring',
    () => field('needle'),
    PipelineFunctions.stringContains,
    (e, v) => e.stringContains(v),
  );
  r.binary(
    'startsWith',
    'title',
    'The',
    () => field('prefix'),
    PipelineFunctions.startsWith,
    (e, v) => e.startsWith(v),
  );
  r.binary(
    'endsWith',
    'title',
    'Rings',
    () => field('suffix'),
    PipelineFunctions.endsWith,
    (e, v) => e.endsWith(v),
  );
  r.binary(
    'stringIndexOf',
    'title',
    'Ring',
    () => field('needle'),
    PipelineFunctions.stringIndexOf,
    (e, v) => e.stringIndexOf(v),
  );
  r.binary(
    'stringRepeat',
    'title',
    2,
    () => field('times'),
    PipelineFunctions.stringRepeat,
    (e, v) => e.stringRepeat(v),
  );
  r.binary(
    'split',
    'csv',
    ',',
    () => field('delimiter'),
    PipelineFunctions.split,
    (e, v) => e.split(v),
    methodAlternatives: [(e, v) => e.splitLiteral(v! as String)],
  );
  r.binary(
    'join',
    'tags',
    ', ',
    () => field('delimiter'),
    PipelineFunctions.join,
    (e, v) => e.join(v),
    methodAlternatives: [(e, v) => e.joinLiteral(v! as String)],
  );

  for (final (name, static, method) in [
    (
      'trim',
      PipelineFunctions.trim,
      (PipelineExpression e, [Object? chars]) => e.trim(chars),
    ),
    (
      'ltrim',
      PipelineFunctions.ltrim,
      (PipelineExpression e, [Object? chars]) => e.ltrim(chars),
    ),
    (
      'rtrim',
      PipelineFunctions.rtrim,
      (PipelineExpression e, [Object? chars]) => e.rtrim(chars),
    ),
  ]) {
    r.unary(name, 'title', static, method);
    r.expr(
      'functions/$name/static-field-name-literal',
      () => static('title', '-'),
    );
    r.expr(
      'functions/$name/static-expression-expression',
      () => static(field('title'), field('chars')),
    );
    r.expr('functions/$name/method-literal', () => method(field('title'), '-'));
    r.expr(
      'functions/$name/method-expression',
      () => method(field('title'), field('chars')),
    );
  }

  r.expr(
    'functions/stringConcat/static-field-name-literal',
    () => PipelineFunctions.stringConcat(['title', ' by ']),
  );
  r.expr(
    'functions/stringConcat/static-field-name-variadic',
    () => PipelineFunctions.stringConcat(['title', ' by ', field('author')]),
  );
  r.expr(
    'functions/stringConcat/static-expression-expression',
    () => PipelineFunctions.stringConcat([field('title'), field('author')]),
  );
  r.expr(
    'functions/stringConcat/method-literal',
    () => field('title').stringConcat([' by ']),
  );
  r.expr(
    'functions/stringConcat/method-variadic',
    () => field('title').stringConcat([' by ', field('author')]),
  );

  r.expr(
    'functions/concat/static-field-name-literal',
    () => PipelineFunctions.concat('title', '!'),
  );
  r.expr(
    'functions/concat/static-expression-variadic',
    () => PipelineFunctions.concat(field('title'), ' by ', [field('author')]),
  );
  r.expr('functions/concat/method-literal', () => field('title').concat(['!']));
  r.expr(
    'functions/concat/method-list',
    () => field('tags').concat([
      ['extra'],
    ]),
  );
  r.expr(
    'functions/concat/method-variadic',
    () => field('title').concat([' by ', field('author')]),
  );

  for (final (name, static, method, literalMethod) in [
    (
      'stringReplaceAll',
      PipelineFunctions.stringReplaceAll,
      (PipelineExpression e, Object? f, Object? t) => e.stringReplaceAll(f, t),
      (PipelineExpression e, String f, String t) =>
          e.stringReplaceAllLiteral(f, t),
    ),
    (
      'stringReplaceOne',
      PipelineFunctions.stringReplaceOne,
      (PipelineExpression e, Object? f, Object? t) => e.stringReplaceOne(f, t),
      (PipelineExpression e, String f, String t) =>
          e.stringReplaceOneLiteral(f, t),
    ),
  ]) {
    r.expr(
      'functions/$name/static-field-name-literals',
      () => static('title', 'a', 'b'),
    );
    r.expr(
      'functions/$name/static-expression-expressions',
      () => static(field('title'), field('find'), field('replacement')),
    );
    r.expr(
      'functions/$name/method-literals',
      () => method(field('title'), 'a', 'b'),
      [() => literalMethod(field('title'), 'a', 'b')],
    );
    r.expr(
      'functions/$name/method-expressions',
      () => method(field('title'), field('find'), field('replacement')),
    );
  }

  r.expr(
    'functions/substring/static-field-name-position',
    () => PipelineFunctions.substring('title', 2),
  );
  r.expr(
    'functions/substring/static-field-name-position-length',
    () => PipelineFunctions.substring('title', 2, 3),
  );
  r.expr(
    'functions/substring/static-expression-expressions',
    () => PipelineFunctions.substring(
      field('title'),
      field('start'),
      field('count'),
    ),
  );
  r.expr(
    'functions/substring/method-position',
    () => field('title').substring(2),
    [() => field('title').substringLiteral(2)],
  );
  r.expr(
    'functions/substring/method-position-length',
    () => field('title').substring(2, 3),
    [() => field('title').substringLiteral(2, 3)],
  );
  r.expr(
    'functions/substring/method-expressions',
    () => field('title').substring(field('start'), field('count')),
  );
}

void _registerArrays(_Registry r) {
  void array(String variant, List<Object?> Function() values) {
    r.expr(
      'functions/array/$variant',
      () => PipelineFunctions.array(values()),
      [() => Expression.array(values())],
    );
  }

  array('static-literals', () => [1, 'a', true, null]);
  array('static-with-expressions', () => [field('title'), 1]);
  array(
    'static-nested',
    () => [
      [1, field('a')],
      {'k': field('b')},
    ],
  );
  array('static-empty', () => []);

  r.expr(
    'functions/arrayConcat/static-field-name-list',
    () => PipelineFunctions.arrayConcat([
      'tags',
      ['x', 'y'],
    ]),
  );
  r.expr(
    'functions/arrayConcat/static-field-name-expression',
    () => PipelineFunctions.arrayConcat(['tags', field('moreTags')]),
  );
  r.expr(
    'functions/arrayConcat/static-expression-variadic',
    () => PipelineFunctions.arrayConcat([
      field('tags'),
      field('moreTags'),
      ['z'],
    ]),
  );
  r.expr(
    'functions/arrayConcat/method-list',
    () => field('tags').arrayConcat(['x', 'y']),
  );
  r.expr(
    'functions/arrayConcat/method-expression',
    () => field('tags').arrayConcat(field('moreTags')),
  );
  r.expr(
    'functions/arrayConcat/method-variadic',
    () => field('tags').arrayConcatMultiple([
      field('moreTags'),
      ['z'],
    ]),
  );

  r.binary(
    'arrayContains',
    'tags',
    'magic',
    () => field('wanted'),
    PipelineFunctions.arrayContains,
    (e, v) => e.arrayContains(v),
  );

  for (final (name, target, values, withExpression, nested, static, method) in [
    (
      'arrayContainsAll',
      'tags',
      ['magic', 'epic'],
      () => ['magic', field('wanted')],
      [
        'magic',
        ['epic'],
      ],
      PipelineFunctions.arrayContainsAll,
      (PipelineExpression e, Object? v) => switch (v) {
        Iterable<Object?>() => e.arrayContainsAll(v),
        _ => e.arrayContainsAllFrom(v),
      },
    ),
    (
      'arrayContainsAny',
      'tags',
      ['magic', 'epic'],
      () => ['magic', field('wanted')],
      [
        'magic',
        ['epic'],
      ],
      PipelineFunctions.arrayContainsAny,
      // PipelineExpression.arrayContainsAny only takes a list; the
      // PipelineFunctions form takes an array expression.
      (PipelineExpression e, Object? v) => switch (v) {
        Iterable<Object?>() => e.arrayContainsAny(v),
        _ => PipelineFunctions.arrayContainsAny(e, v),
      },
    ),
    (
      'equalAny',
      'genre',
      ['Fantasy', 'Sci-Fi'],
      () => ['Fantasy', field('favorite')],
      [
        'Fantasy',
        ['Sci-Fi'],
      ],
      PipelineFunctions.equalAny,
      (PipelineExpression e, Object? v) => e.equalAny(v),
    ),
    (
      'notEqualAny',
      'genre',
      ['Fantasy', 'Sci-Fi'],
      () => ['Fantasy', field('favorite')],
      [
        'Fantasy',
        ['Sci-Fi'],
      ],
      PipelineFunctions.notEqualAny,
      (PipelineExpression e, Object? v) => e.notEqualAny(v),
    ),
  ]) {
    final arrayExpression = target == 'tags' ? 'wanted' : 'genres';
    r.expr(
      'functions/$name/static-field-name-list',
      () => static(target, values),
    );
    r.expr(
      'functions/$name/static-field-name-list-with-expression',
      () => static(target, withExpression()),
    );
    r.expr(
      'functions/$name/static-field-name-list-nested',
      () => static(target, nested),
    );
    r.expr(
      'functions/$name/static-field-name-array-expression',
      () => static(target, field(arrayExpression)),
    );
    r.expr(
      'functions/$name/static-expression-list',
      () => static(field(target), values),
    );
    r.expr('functions/$name/method-list', () => method(field(target), values));
    r.expr(
      'functions/$name/method-list-with-expression',
      () => method(field(target), withExpression()),
    );
    r.expr(
      'functions/$name/method-array-expression',
      () => method(field(target), field(arrayExpression)),
    );
  }

  r.unary(
    'arrayLength',
    'tags',
    PipelineFunctions.arrayLength,
    (e) => e.arrayLength(),
  );
  r.unary(
    'arrayFirst',
    'tags',
    PipelineFunctions.arrayFirst,
    (e) => e.arrayFirst(),
  );
  r.unary(
    'arrayLast',
    'tags',
    PipelineFunctions.arrayLast,
    (e) => e.arrayLast(),
  );
  r.unary(
    'arrayReverse',
    'tags',
    PipelineFunctions.arrayReverse,
    (e) => e.arrayReverse(),
  );
  r.unary('arraySum', 'tags', PipelineFunctions.arraySum, (e) => e.arraySum());
  r.unary(
    'arrayMaximum',
    'tags',
    PipelineFunctions.arrayMaximum,
    (e) => e.arrayMaximum(),
  );
  r.unary(
    'arrayMinimum',
    'tags',
    PipelineFunctions.arrayMinimum,
    (e) => e.arrayMinimum(),
  );

  r.binary(
    'arrayFirstN',
    'scores',
    2,
    () => field('n'),
    PipelineFunctions.arrayFirstN,
    (e, v) => e.arrayFirstN(v),
  );
  r.binary(
    'arrayLastN',
    'scores',
    2,
    () => field('n'),
    PipelineFunctions.arrayLastN,
    (e, v) => e.arrayLastN(v),
  );
  r.binary(
    'arrayMaximumN',
    'scores',
    2,
    () => field('n'),
    PipelineFunctions.arrayMaximumN,
    (e, v) => e.arrayMaximumN(v),
  );
  r.binary(
    'arrayMinimumN',
    'scores',
    2,
    () => field('n'),
    PipelineFunctions.arrayMinimumN,
    (e, v) => e.arrayMinimumN(v),
  );
  r.binary(
    'arrayGet',
    'tags',
    1,
    () => field('index'),
    PipelineFunctions.arrayGet,
    (e, v) => e.arrayGet(v),
  );
  r.binary(
    'arrayIndexOf',
    'tags',
    'magic',
    () => field('wanted'),
    PipelineFunctions.arrayIndexOf,
    (e, v) => e.arrayIndexOf(v),
  );
  r.binary(
    'arrayLastIndexOf',
    'tags',
    'magic',
    () => field('wanted'),
    PipelineFunctions.arrayLastIndexOf,
    (e, v) => e.arrayLastIndexOf(v),
  );
  r.binary(
    'arrayIndexOfAll',
    'tags',
    'magic',
    () => field('wanted'),
    PipelineFunctions.arrayIndexOfAll,
    (e, v) => e.arrayIndexOfAll(v),
  );

  r.expr(
    'functions/arraySlice/static-field-name-offset-length',
    () => PipelineFunctions.arraySlice('tags', 1, 2),
  );
  r.expr(
    'functions/arraySlice/static-expression-expressions',
    () => PipelineFunctions.arraySlice(
      field('tags'),
      field('start'),
      field('count'),
    ),
  );
  r.expr(
    'functions/arraySlice/method-offset',
    () => field('tags').arraySlice(1),
  );
  r.expr(
    'functions/arraySlice/method-offset-length',
    () => field('tags').arraySlice(1, 2),
  );
  r.expr(
    'functions/arraySlice/method-expressions',
    () => field('tags').arraySlice(field('start'), field('count')),
  );

  PipelineBooleanExpression isMagic() => variable('tag').equal('magic');
  r.expr(
    'functions/arrayFilter/static-field-name',
    () => PipelineFunctions.arrayFilter('tags', 'tag', isMagic()),
  );
  r.expr(
    'functions/arrayFilter/static-expression',
    () => PipelineFunctions.arrayFilter(field('tags'), 'tag', isMagic()),
  );
  r.expr(
    'functions/arrayFilter/method',
    () => field('tags').arrayFilter('tag', isMagic()),
  );

  PipelineExpression upper() => variable('tag').toUpperCase();
  r.expr(
    'functions/arrayTransform/static-field-name',
    () => PipelineFunctions.arrayTransform('tags', 'tag', upper()),
  );
  r.expr(
    'functions/arrayTransform/static-expression',
    () => PipelineFunctions.arrayTransform(field('tags'), 'tag', upper()),
  );
  r.expr(
    'functions/arrayTransform/method',
    () => field('tags').arrayTransform('tag', upper()),
  );

  PipelineExpression indexed() => variable('tag').stringConcat([variable('i')]);
  r.expr(
    'functions/arrayTransformWithIndex/static-field-name',
    () => PipelineFunctions.arrayTransformWithIndex(
      'tags',
      'tag',
      'i',
      indexed(),
    ),
  );
  r.expr(
    'functions/arrayTransformWithIndex/static-expression',
    () => PipelineFunctions.arrayTransformWithIndex(
      field('tags'),
      'tag',
      'i',
      indexed(),
    ),
  );
  r.expr(
    'functions/arrayTransformWithIndex/method',
    () => field('tags').arrayTransformWithIndex('tag', 'i', indexed()),
  );
}

void _registerMaps(_Registry r) {
  r.expr(
    'functions/map/static-literals',
    () => PipelineFunctions.map(['a', 1, 'b', 'x']),
  );
  r.expr(
    'functions/map/static-with-expressions',
    () => PipelineFunctions.map(['a', field('title'), 'b', 1]),
  );
  r.expr(
    'functions/map/static-nested',
    () => PipelineFunctions.map([
      'inner',
      {'k': field('y')},
      'list',
      [field('z'), 1],
    ]),
  );
  r.expr('functions/map/static-empty', () => PipelineFunctions.map([]));

  r.expr(
    'functions/mapGet/static-field-name',
    () => PipelineFunctions.mapGet('metadata', 'lang'),
  );
  r.expr(
    'functions/mapGet/static-expression',
    () => PipelineFunctions.mapGet(field('metadata'), 'lang'),
  );
  r.expr('functions/mapGet/method', () => field('metadata').mapGet('lang'), [
    () => field('metadata').mapGetLiteral('lang'),
  ]);

  r.expr(
    'functions/mapSet/static-field-name-literal',
    () => PipelineFunctions.mapSet('metadata', ['lang', 'en']),
  );
  r.expr(
    'functions/mapSet/static-expression-variadic',
    () => PipelineFunctions.mapSet(field('metadata'), [
      'lang',
      'en',
      'pages',
      field('pageCount'),
    ]),
  );
  r.expr(
    'functions/mapSet/method-literal',
    () => field('metadata').mapSet('lang', 'en'),
  );
  r.expr(
    'functions/mapSet/method-expression-key',
    () => field('metadata').mapSet(field('key'), field('value')),
  );
  r.expr(
    'functions/mapSet/method-variadic',
    () => field('metadata').mapSet('lang', 'en', ['pages', field('pageCount')]),
  );

  r.binary(
    'mapRemove',
    'metadata',
    'lang',
    () => field('key'),
    PipelineFunctions.mapRemove,
    (e, v) => e.mapRemove(v),
  );

  r.expr(
    'functions/mapMerge/static-field-name-map',
    () => PipelineFunctions.mapMerge([
      'metadata',
      {'extra': 1},
    ]),
  );
  r.expr(
    'functions/mapMerge/static-expression-expression',
    () => PipelineFunctions.mapMerge([field('metadata'), field('overrides')]),
  );
  r.expr(
    'functions/mapMerge/static-field-name-variadic',
    () => PipelineFunctions.mapMerge([
      'metadata',
      {'extra': field('title')},
      field('overrides'),
    ]),
  );
  r.expr(
    'functions/mapMerge/method-map',
    () => field('metadata').mapMerge([
      {'extra': 1},
    ]),
  );
  r.expr(
    'functions/mapMerge/method-variadic',
    () => field('metadata').mapMerge([
      {'extra': field('title')},
      field('overrides'),
    ]),
  );

  r.unary('mapKeys', 'metadata', PipelineFunctions.mapKeys, (e) => e.mapKeys());
  r.unary(
    'mapValues',
    'metadata',
    PipelineFunctions.mapValues,
    (e) => e.mapValues(),
  );
  r.unary(
    'mapEntries',
    'metadata',
    PipelineFunctions.mapEntries,
    (e) => e.mapEntries(),
  );
  r.binary(
    'getField',
    'metadata',
    'lang',
    () => field('key'),
    PipelineFunctions.getField,
    (e, v) => e.getField(v),
  );
}

void _registerTimestamps(_Registry r) {
  r.unary(
    'unixMicrosToTimestamp',
    'published',
    PipelineFunctions.unixMicrosToTimestamp,
    (e) => e.unixMicrosToTimestamp(),
  );
  r.unary(
    'unixMillisToTimestamp',
    'published',
    PipelineFunctions.unixMillisToTimestamp,
    (e) => e.unixMillisToTimestamp(),
  );
  r.unary(
    'unixSecondsToTimestamp',
    'published',
    PipelineFunctions.unixSecondsToTimestamp,
    (e) => e.unixSecondsToTimestamp(),
  );
  r.unary(
    'timestampToUnixMicros',
    'published',
    PipelineFunctions.timestampToUnixMicros,
    (e) => e.timestampToUnixMicros(),
  );
  r.unary(
    'timestampToUnixMillis',
    'published',
    PipelineFunctions.timestampToUnixMillis,
    (e) => e.timestampToUnixMillis(),
  );
  r.unary(
    'timestampToUnixSeconds',
    'published',
    PipelineFunctions.timestampToUnixSeconds,
    (e) => e.timestampToUnixSeconds(),
  );

  for (final (name, static, method) in [
    (
      'timestampAdd',
      PipelineFunctions.timestampAdd,
      (PipelineExpression e, Object? unit, Object? amount) =>
          e.timestampAdd(unit, amount),
    ),
    (
      'timestampSubtract',
      PipelineFunctions.timestampSubtract,
      (PipelineExpression e, Object? unit, Object? amount) =>
          e.timestampSubtract(unit, amount),
    ),
  ]) {
    r.expr(
      'functions/$name/static-field-name-literals',
      () => static('published', 'day', 1),
    );
    r.expr(
      'functions/$name/static-expression-literals',
      () => static(field('published'), 'hour', 2),
    );
    r.expr(
      'functions/$name/static-expression-expressions',
      () => static(field('published'), field('unit'), field('amount')),
    );
    r.expr(
      'functions/$name/method-literals',
      () => method(field('published'), 'minute', 30),
    );
    r.expr(
      'functions/$name/method-expressions',
      () => method(field('published'), field('unit'), field('amount')),
    );
  }

  for (final (name, static, method, literal, timezoneLiteral, methodLiteral)
      in [
        (
          'timestampTruncate',
          PipelineFunctions.timestampTruncate,
          (PipelineExpression e, Object? unit, [Object? timezone]) =>
              e.timestampTruncate(unit, timezone),
          'day',
          'week(monday)',
          'year',
        ),
        (
          'timestampExtract',
          PipelineFunctions.timestampExtract,
          (PipelineExpression e, Object? part, [Object? timezone]) =>
              e.timestampExtract(part, timezone),
          'year',
          'dayofweek',
          'dayofyear',
        ),
      ]) {
    final unit = name == 'timestampTruncate' ? 'granularity' : 'part';
    final literalWithTimezone = name == 'timestampTruncate' ? 'day' : 'hour';
    r.expr(
      'functions/$name/static-field-name-literal',
      () => static('published', literal),
    );
    r.expr(
      'functions/$name/static-field-name-literal-timezone',
      () => static('published', timezoneLiteral, 'America/New_York'),
    );
    r.expr(
      'functions/$name/static-expression-expression',
      () => static(field('published'), field(unit)),
    );
    r.expr(
      'functions/$name/static-expression-timezone-expression',
      () => static(field('published'), 'month', field('tz')),
    );
    r.expr(
      'functions/$name/method-literal',
      () => method(field('published'), methodLiteral),
    );
    r.expr(
      'functions/$name/method-literal-timezone',
      () => method(field('published'), literalWithTimezone, 'UTC'),
    );
    r.expr(
      'functions/$name/method-expression-timezone-expression',
      () => method(field('published'), field(unit), field('tz')),
    );
  }

  r.expr(
    'functions/timestampDiff/static-field-names',
    () => PipelineFunctions.timestampDiff('end', 'start', 'day'),
  );
  r.expr(
    'functions/timestampDiff/static-field-name-expression',
    () => PipelineFunctions.timestampDiff('end', field('start'), 'second'),
  );
  r.expr(
    'functions/timestampDiff/static-expression-field-name',
    () => PipelineFunctions.timestampDiff(field('end'), 'start', 'hour'),
  );
  r.expr(
    'functions/timestampDiff/static-expressions-unit-expression',
    () => PipelineFunctions.timestampDiff(
      field('end'),
      field('start'),
      field('unit'),
    ),
  );
  r.expr(
    'functions/timestampDiff/method-field-name',
    () => field('end').timestampDiff('start', 'day'),
  );
  r.expr(
    'functions/timestampDiff/method-expressions',
    () => field('end').timestampDiff(field('start'), field('unit')),
  );
  r.expr(
    'functions/currentTimestamp/static',
    PipelineFunctions.currentTimestamp,
  );
}

void _registerTypesVectorsAndReferences(_Registry r) {
  r.unary('type', 'value', PipelineFunctions.type, (e) => e.type());
  r.expr(
    'functions/isType/static-field-name',
    () => PipelineFunctions.isType('value', PipelineValueType.string),
    [() => PipelineFunctions.isType('value', 'string')],
  );
  r.expr(
    'functions/isType/static-expression',
    () => PipelineFunctions.isType(field('value'), PipelineValueType.string),
    [() => PipelineFunctions.isType(field('value'), 'string')],
  );
  for (final (name, type) in [
    ('null', PipelineValueType.nullValue),
    ('array', PipelineValueType.array),
    ('boolean', PipelineValueType.boolean),
    ('bytes', PipelineValueType.bytes),
    ('timestamp', PipelineValueType.timestamp),
    ('geo_point', PipelineValueType.geoPoint),
    ('number', PipelineValueType.number),
    ('int32', PipelineValueType.int32),
    ('int64', PipelineValueType.int64),
    ('float64', PipelineValueType.double),
    ('decimal128', PipelineValueType.decimal128),
    ('map', PipelineValueType.map),
    ('reference', PipelineValueType.reference),
    ('string', PipelineValueType.string),
    ('vector', PipelineValueType.vector),
    ('max_key', PipelineValueType.maxKey),
    ('min_key', PipelineValueType.minKey),
    ('object_id', PipelineValueType.objectId),
    ('regex', PipelineValueType.regex),
    // No PipelineValueType member: isType takes the raw name.
    ('request_timestamp', null),
  ]) {
    final id = 'functions/isType/method-${name.replaceAll('_', '-')}';
    if (type == null) {
      r.expr(id, () => field('value').isType(name));
    } else {
      r.expr(id, () => field('value').isType(type), [
        () => field('value').isType(name),
      ]);
    }
  }

  for (final (name, static, method) in [
    (
      'cosineDistance',
      PipelineFunctions.cosineDistance,
      (PipelineExpression e, Object? v) => e.cosineDistance(v),
    ),
    (
      'dotProduct',
      PipelineFunctions.dotProduct,
      (PipelineExpression e, Object? v) => e.dotProduct(v),
    ),
    (
      'euclideanDistance',
      PipelineFunctions.euclideanDistance,
      (PipelineExpression e, Object? v) => e.euclideanDistance(v),
    ),
  ]) {
    r.expr(
      'functions/$name/static-field-name-number-array',
      () => static('embedding', const [0.1, 0.2, 0.3]),
    );
    r.expr(
      'functions/$name/static-field-name-integer-array',
      () => static('embedding', const [1, 2, 3]),
    );
    r.expr(
      'functions/$name/static-field-name-vector-value',
      () => static('embedding', _vector),
      [
        () => static('embedding', Expression.vector([0.1, 0.2, 0.3])),
      ],
    );
    r.expr(
      'functions/$name/static-field-name-expression',
      () => static('embedding', field('other')),
    );
    r.expr(
      'functions/$name/static-expression-number-array',
      () => static(field('embedding'), const [0.1, 0.2, 0.3]),
    );
    r.expr(
      'functions/$name/static-expression-expression',
      () => static(field('embedding'), field('other')),
    );
    r.expr(
      'functions/$name/method-number-array',
      () => method(field('embedding'), const [0.1, 0.2, 0.3]),
    );
    r.expr(
      'functions/$name/method-vector-value',
      () => method(field('embedding'), _vector),
    );
    r.expr(
      'functions/$name/method-expression',
      () => method(field('embedding'), field('other')),
    );
  }
  r.unary(
    'vectorLength',
    'embedding',
    PipelineFunctions.vectorLength,
    (e) => e.vectorLength(),
  );

  r.expr(
    'functions/geoDistance/static-field-name-geo-point',
    () => PipelineFunctions.geoDistance('location', _geoPoint),
  );
  r.expr(
    'functions/geoDistance/static-field-geo-point',
    () => PipelineFunctions.geoDistance(field('location'), _geoPoint),
  );
  r.expr(
    'functions/geoDistance/static-field-name-expression',
    () => PipelineFunctions.geoDistance('location', field('other')),
  );
  r.expr(
    'functions/geoDistance/method-geo-point',
    () => field('location').geoDistance(_geoPoint),
  );
  r.expr(
    'functions/geoDistance/method-expression',
    () => field('location').geoDistance(field('other')),
  );

  r.unary(
    'collectionId',
    '__name__',
    PipelineFunctions.collectionId,
    (e) => e.collectionId(),
  );
  for (final (name, static, method) in [
    (
      'documentId',
      PipelineFunctions.documentId,
      (PipelineExpression e) => e.documentId(),
    ),
    ('parent', PipelineFunctions.parent, (PipelineExpression e) => e.parent()),
  ]) {
    r.expr('functions/$name/static-path', () => static('books/book1'));
    r.dbExpr('functions/$name/static-reference', (db) => static(_docRef(db)));
    r.expr(
      'functions/$name/static-expression',
      () => static(field('__name__')),
    );
    r.expr('functions/$name/method', () => method(field('__name__')));
  }

  r.expr(
    'functions/currentDocument/static',
    PipelineFunctions.currentDocument,
    [currentDocument],
  );
  r.expr(
    'functions/documentMatches/static-literal',
    () => PipelineFunctions.documentMatches('breakfast'),
    [() => documentMatches('breakfast')],
  );
  r.expr(
    'functions/documentMatches/static-expression',
    () => PipelineFunctions.documentMatches(field('query')),
    [() => documentMatches(field('query'))],
  );
  r.expr('functions/score/static', PipelineFunctions.score, [score]);
}

void _registerAggregates(_Registry r) {
  r.aggregate('aggregates/countAll/static', PipelineFunctions.countAll, [
    PipelineFunctions.count,
  ]);
  for (final (name, static, method) in <(String, _Static1, _Method0)>[
    ('count', PipelineFunctions.count, (e) => e.count()),
    ('sum', PipelineFunctions.sum, (e) => e.sum()),
    ('average', PipelineFunctions.average, (e) => e.average()),
    ('minimum', PipelineFunctions.minimum, (e) => e.minimum()),
    ('maximum', PipelineFunctions.maximum, (e) => e.maximum()),
    ('first', PipelineFunctions.first, (e) => e.first()),
    ('last', PipelineFunctions.last, (e) => e.last()),
    ('arrayAgg', PipelineFunctions.arrayAgg, (e) => e.arrayAgg()),
    (
      'arrayAggDistinct',
      PipelineFunctions.arrayAggDistinct,
      (e) => e.arrayAggDistinct(),
    ),
    (
      'countDistinct',
      PipelineFunctions.countDistinct,
      (e) => e.countDistinct(),
    ),
  ]) {
    r.unary(name, 'rating', static, method, area: 'aggregates');
  }
  r.aggregate(
    'aggregates/countIf/static',
    () => PipelineFunctions.countIf(_isGood()),
  );
  r.aggregate('aggregates/countIf/method', () => _isGood().countIf());
}
